# Generated by Django 2.2.1 on 2019-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudsimple',
            name='nim',
            field=models.IntegerField(),
        ),
    ]
